### ISSUE TITLE
Form Events and Compatibility with upcoming release Igor

### ISSUE THREAD

**Issue by splitbrain** [turnermm/tplmod#14]
This plugin seems to make use of one or more form related action events that will be removed in the next DokuWiki release. Please have a look at https://www.patreon.com/posts/better-forms-58551930 for details.

My apologies if this has already been addressed in your code. If you have any questions on how to implement the needed changes please let me know.

**Comment by turnermm** [comment]
Updated user profile form to handle new Form library:
https://github.com/turnermm/tplmod/commit/54d2d77dca40ec159777d7e2b92abe0201800b81
