### ISSUE TITLE
missing quotes in action.php line 10?

### ISSUE THREAD

**Issue by ggieling** [turnermm/tplmod#2]
My test site (with PHP notice set to the most strict option) reports the following after installing tplmod in dokuwiki:
`Warning: Use of undefined constant DOKUWIKI_STARTED - assumed 'DOKUWIKI_STARTED' (this will throw an Error in a future version of PHP) in /srv/http/won1/dokuwiki/lib/plugins/tplmod/action.php on line 10`
Lines 10-12 of action.php read as follows
`10       $controller->register_hook(DOKUWIKI_STARTED, 'BEFORE', $this, 'dwstarted');`
`11        $controller->register_hook('TEMPLATE_SITETOOLS_DISPLAY', 'BEFORE', $this, 'action_link', array('site'));`
`12        $controller->register_hook('MENU_ITEMS_ASSEMBLY', 'AFTER', $this, 'addsvgbutton', array());`

I guess that in line 10 the parameter DOKUWIKI_STARTED should be enlosed by single quotes similar to the parameters 'TEMPLATE_SITETOOLS_DISPLAY' and 'MENU_ITEMS_ASSEMBLY' in lines 11 and 12.

**Comment by turnermm** [comment]
Thanks. Fixed.
