### ISSUE TITLE
Site tools & page tools are still shown in mobile tools

### ISSUE THREAD

**Issue by eilko** [turnermm/tplmod#4]
When I use my Android phone in portrait mode, it shows the mobile tools and only the options I allowed
 
![screenshot_20180514-081430](https://user-images.githubusercontent.com/1078401/39994499-d10447e6-5779-11e8-9f33-394b2175a995.png)

But when I use my iPhone X in portrait mode the mobile tools shows all options, including the site tools like media manager. When I turn the iPhone to landscape mode the normal size website is shown (except for the sidebar) but the site tools are gone and only the correct page tools are shown.

![img_0368](https://user-images.githubusercontent.com/1078401/39994516-df3407d4-5779-11e8-9078-b11055ff6495.PNG)

**Comment by eilko** [comment]
thanks, you are right also on an iMac Safari behaves different from Chrome and Firefox. I didn't notice before.

**Comment by turnermm** [comment]
I've been checking to see if there's an alternate solution, but haven't had any success yet.
